server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        webAllowOthers: true
  jpa:
    showSql: true
    ddlAuto: create